clone:
  environment:
  - GIT_SSL_NO_VERIFY=true
publish:
  docker:
    environment:
    - DOCKER_LAUNCH_DEBUG=true
    file: Dockerfile
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PWD
    email: lars.mogren@gmail.com
    repo: kodbasen/fluentd-es-armhf
    tag:
    - "0.14.0.pre.1"
    - latest
